export const ENDPOINTS = {
  collections: '/api/collections',
  collectionBySlug: (slug) => `/api/collections/${slug}`,
  categories: '/api/categories',
  categoryById: (id) => `/api/categories/${id}`,
  products: '/api/products',
  productById: (id) => `/api/products/${id}`,
  cart: '/api/cart',
  cartItems: '/api/cart/items',
  cartItem: (itemId) => `/api/cart/items/${itemId}`,
  cartMerge: '/api/cart/merge',
  banners: '/api/banners',
  bannersActive: '/api/banners/active',
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    verify: '/api/auth/verify',
    profile: '/api/user/profile',
    logout: '/api/auth/logout',
    refresh: '/api/auth/refresh',
  },
  user: {
    profile: '/api/user/profile',
    avatar: '/api/user/avatar',
    byId: (id) => `/api/user/${id}`,
  },
  address: '/api/address',
  addressById: (id) => `/api/address/${id}`,
  order: '/api/orders',
  orderByUser: '/api/orders/me',
  orderCancel: (id) => `/api/orders/${id}`,
  orderUpdatePayment: '/api/orders/payments',
  fileUpload: '/api/file',
};
